### ISSUE TITLE
Board 엔티티 isPublic 변수 getter 작성 오류 in BoardMapper

### ISSUE THREAD

**Issue by rt3310** [C-B-U/owl-forest#101]
BoardMapper line 28
`.isPublic(entity.isPublic())` 구문 오류가 있습니다

- @Getter 적용 시
  - Boolean 객체 사용 -> prefix: `get`
  - boolean 타입 사용 -> prefix: `is`

해당 변수는 Boolean 객체로 작성되어 수정이 필요할 것 같습니다.

**Comment by phjppo0918** [comment]
오우 실제로 안돌리고 뇌버깅으로만 했는데 ㅋㅋㅋㅋㅋㅋㅋㅋ 저런 오류가 있었다니;;
감사합니다!
