### ISSUE TITLE
build.gradle security 중복 작성 수정

### ISSUE THREAD

**Issue by rt3310** [C-B-U/owl-forest#196]
### Description

> build.gradle에 security가 중복 작성되어 가끔 인식이 안되는 경우가 생기는 것 같습니다.

### To-do

- [ ] security implementation 하나 삭제

### ETC

**Comment by phjppo0918** [comment]
제가 확인해봤는데 중복된 부분이 없는데...!

**Comment by rt3310** [comment]
<img width="636" alt="스크린샷 2023-01-19 14 00 42" src="https://user-images.githubusercontent.com/66542103/213359353-5d0b65b1-ab2c-4c43-a258-8be4e15dc7dc.png">
혹시 46, 52 번째줄에 같은거 안적혀있으신가요,,ㅠㅠ

**Comment by phjppo0918** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/55674648/213365837-0823e16b-4421-41ae-93bb-afde94bd0d8d.png">
현재 main 상태입니다!
